### PR TITLE
(MAINT) Set up Travis

### PR DESCRIPTION
**Pull request by fpringvaldsen**

### CODE REVIEW

**Comment by rlinehan** [comment]
Hm, seems like travis is working properly, but it seems like it's failed a couple times on ruby 2.2.0 (it failed once and then I reran it and it failed again).

```
/home/travis/.rvm/gems/ruby-2.2.0/gems/puppet-3.7.5/lib/puppet/vendor/safe_yaml/lib/safe_yaml/syck_node_monkeypatch.rb:42:in `<top (required)>': uninitialized constant Syck (NameError)

	from /home/travis/.rvm/gems/ruby-2.2.0/gems/puppet-3.7.5/lib/puppet/vendor/safe_yaml/lib/safe_yaml.rb:197:in `require'
```
I get this if I run the tests locally against 2.2.0 too.

Should we just merge this and have travis fail? Or comment out 2.2.0 support until we've fixed it? I think I would prefer commenting out 2.2.0, rather than merging and having it be failing.

Also, it doesn't seem like this is currently reporting to HipChat?

**Comment by fpringvaldsen** [comment]
@rlinehan I agree, I'm going to comment out 2.2.0 support. I'll also look into fixing the Hipchat notifications.

**Comment by fpringvaldsen** [comment]
@rlinehan I've removed 2.2.0 support. Also, I added hipchat notifications.

**Comment by fpringvaldsen** [comment]
@rlinehan Okay, hopefully notifications will work this time

**Comment by fpringvaldsen** [comment]
Okay, maybe this time it'll work

**Comment by rlinehan** [comment]
:+1: Hipchat notifications are maybe not working even though it seems like they should be, so just going to go ahead and merge because maybe they're just not working because this PR has been force pushed so many times? Who knows.

**Pull request merged**
