### PR TITLE
Supported OS Update

### PR DESCRIPTION
**Pull request by trevor-vaughan**
* Add support for CentOS, RHEL, and OEL to metadata.json
* Fix some errors in the CHANGELOG.md

### CODE REVIEW

**Comment by david22swan** [comment]
@trevor-vaughan Have you tested on these OS?? This is not a supported module so there is no pipeline for me to consult.

**Comment by trevor-vaughan** [comment]
@david22swan Yes. We actively use it as part of the SIMP stack which runs on these operating systems.

**Comment by david22swan** [comment]
@trevor-vaughan Ok, didn't notice this earlier, but any reason for you bumping the version number???

**Comment by trevor-vaughan** [comment]
@david22swan I can switch it back, or you can push to the branch if you need to change it back. Just wanted to indicate that this has progressed beyond the last release.

**Comment by david22swan** [comment]
@trevor-vaughan I'd prefer it if you could put it back please. Version bumps should only be done as part of the release cycle.

**Comment by trevor-vaughan** [comment]
@david22swan Appreciated!

**Pull request merged**
