### PR TITLE
Remove unnecessary hocon require, add write_conf method

### PR DESCRIPTION
**Pull request by highb**
Prior to this commit we had a separate config_saver module
for saving the hocon config to disk. This module was requiring
the hocon gem without Puppet feature protection. This was causing
requirement issues on the Puppet Server side, where the hocon gem
is not typically installed.

This commit moves the code from config saver into the main hocon
provider, as the method write_conf. This removes the unnecessary
require, and cleans up the unnecessary config_saver module.

### CODE REVIEW

**Comment by jpinsonault** [comment]
Looks good to me assuming travis passes.

**Comment by highb** [comment]
Whenever *that* happens.

**Comment by highb** [comment]
@jpinsonault CI passed. :)

**Comment by jpinsonault** [comment]
Since it's such a simple change I'll go ahead and merge it. Mentioning @fpringvaldsen because he will want to know the PR exists I'm sure

**Pull request merged**
