### PR TITLE
(FM-5972) gettext and spec.opts

### PR DESCRIPTION
**Pull request by eputnam**

### CODE REVIEW

**Comment by hunner** [comment]
https://github.com/puppetlabs/modulesync_configs/pull/114
https://github.com/puppetlabs/modulesync_configs/pull/112

**Comment by haus** [comment]
I don't see `spec.opts` here.

**Comment by hunner** [comment]
This repo must have not had it, so just the gettext fix applies.

**Comment by tphoney** [comment]
thanks @eputnam

**Pull request merged**
